TimeZone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('TimeZone/', include('TimeZoneApp.urls'))
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# if not settings.DEBUG:
#     urlpatterns += [
#         url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
#         url(r'^static/(?P<path>.*)$', 'django.views.static.serve',
#             {'document_root': settings.STATIC_ROOT}),
#     ]

TimeZoneApp/urls.py
from django.urls import path
from . import views
from .views import ProductSearch

urlpatterns = [
    path('register', views.register_user, name='register'),
    path('about', views.about, name='about'),
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('auth', views.auth_token, name='auth'),
    path('verify/<auth_token>', views.auth_verify, name='auth_verify'),
    path('success', views.auth_success, name='auth_success'),
    path('', views.index, name='index'),
    path('contactus', views.contact_us,name='contactus'),
    path('uploadproduct', views.upload_prod, name="uploadproduct"),
    path('shopproducts/', views.shop_prod, name="shopproducts"),
    path('shopproducts/<slug:slug>/', views.product, name="product"),
    path('cart/',views.show_cart,name='cart'),
    path('add_cart/<slug:product_id>', views.add_to_cart, name='add_cart'),
    path('checkout',views.checkout,name='checkout'),
    # path('fake',ProductSearch.as_view(),name='search'),
    # path('product_details', views.product_details, name="product_details"),
    #path('error', views.auth_error, name='auth_error')

]

htmx_urlpatterns = [
    path('check_username', views.check_username, name='check_username'),
    path('check_email', views.check_email, name='check_email'),
    path('check_fname', views.check_fname, name='check_fname'),
    path('check_lname', views.check_lname, name='check_lname'),
    path('search_product', views.search_product, name='search'),
    path('cart/getprice/',views.get_total_price, name='totalPrice'),
]

urlpatterns += htmx_urlpatterns

TimeZoneApp/models.py
from django.db import models
from django import forms
from phonenumber_field.modelfields import PhoneNumberField
import uuid
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save,post_delete
from django.core.validators import MinValueValidator,MaxValueValidator
# Create your function here.


def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>

    try:
        obj = instance.product_uuid
        filename = filename.split('.')[-1]
        return 'TimeZoneApp/Thumbnails/user_{0}/{1}'.format(obj, 'thumbnail.' + filename)
    except:
        obj = instance.product.product_uuid

    return 'TimeZoneApp/Thumbnails/user_{0}/{1}'.format(obj, filename)


# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    auth_token = models.CharField(max_length=200)
    is_verified = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Contact(models.Model):
    sno = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200,null=False)
    email = models.CharField(max_length=200, null=False)
    content = models.TextField()
    subject = models.CharField(max_length=200, null=False)
    timeStamp = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.name+":"+self.subject


class Product(models.Model):
    product_uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    product_name = models.CharField(max_length=200, null=False)
    product_brand = models.CharField(max_length=200, null=False)
    product_price = models.DecimalField(max_digits=12, decimal_places=2)
    product_description = models.TextField()
    product_stocks = models.IntegerField(null=False)
    product_thumbnail = models.ImageField(upload_to=user_directory_path)
    product_like = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product_name+":"+str(self.product_uuid)


class ProductImages(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    images = models.ImageField(upload_to=user_directory_path)

    def __str__(self):
        return self.product.product_name

class UserCart(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    total_price = models.DecimalField(max_digits=12,decimal_places=2,null=False,default=0.00)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20,null=False)
    # shiping_address =
    coupon_code = models.CharField(max_length=50)
    payment_method = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.user_id.username}'s cart"

    def get_total_price(self):
        total=0

        for cart_item in self.usercartproducts_set.all():
            price = cart_item.product_id.product_price
            quantity = cart_item.quantity
            total+= price*quantity

        return total

class UserCartProducts(models.Model):
    id = models.AutoField(primary_key=True)
    usercart_id = models.ForeignKey('UserCart', on_delete=models.CASCADE)
    product_id = models.ForeignKey('Product', on_delete=models.DO_NOTHING)
    quantity = models.IntegerField(null=False,
                                   default=1,
                                   validators=[MinValueValidator(1),MaxValueValidator(10)])
    def __str__(self):
        return f"{self.usercart_id.user_id.username}'s {self.product_id.product_name} x{self.quantity}"

class Address(models.Model):
    STATE_CHOICES = (
        ("AN", "Andaman and Nicobar Islands"),
        ("AP", "Andhra Pradesh"),
        ("AR", "Arunachal Pradesh"),
        ("AS", "Assam"),
        ("BR", "Bihar"),
        ("CG", "Chhattisgarh"),
        ("CH", "Chandigarh"),
        ("DN", "Dadra and Nagar Haveli"),
        ("DD", "Daman and Diu"),
        ("DL", "Delhi"),
        ("GA", "Goa"),
        ("GJ", "Gujarat"),
        ("HR", "Haryana"),
        ("HP", "Himachal Pradesh"),
        ("JK", "Jammu and Kashmir"),
        ("JH", "Jharkhand"),
        ("KA", "Karnataka"),
        ("KL", "Kerala"),
        ("LA", "Ladakh"),
        ("LD", "Lakshadweep"),
        ("MP", "Madhya Pradesh"),
        ("MH", "Maharashtra"),
        ("MN", "Manipur"),
        ("ML", "Meghalaya"),
        ("MZ", "Mizoram"),
        ("NL", "Nagaland"),
        ("OD", "Odisha"),
        ("PB", "Punjab"),
        ("PY", "Pondicherry"),
        ("RJ", "Rajasthan"),
        ("SK", "Sikkim"),
        ("TN", "Tamil Nadu"),
        ("TS", "Telangana"),
        ("TR", "Tripura"),
        ("UP", "Uttar Pradesh"),
        ("UK", "Uttarakhand"),
        ("WB", "West Bengal")
    )
    state = models.CharField(choices=STATE_CHOICES,max_length=50,null=False,default='MH')
    address_line1 = models.CharField(max_length=500,null= False)
    address_line2 = models.CharField(max_length=500,null= False)
    first_name = models.CharField(max_length=50,null=False)
    last_name = models.CharField(max_length=50,null=False)
    district = models.CharField(max_length=50,null=False)
    phone = PhoneNumberField()
    pincode = models.IntegerField(
        validators=[MinValueValidator(100000), MaxValueValidator(999999)],
        blank=True
    )
    landmark = models.CharField(max_length=200,null=False)
    ADDRESS_TYPES = [
        ('home', 'Home'),
        ('work', 'Work'),
    ]
    type = models.CharField(choices=ADDRESS_TYPES, default='home', max_length=10)


@receiver(post_save,sender=UserCartProducts)
@receiver(post_delete,sender=UserCartProducts)
def update_cart_total_price(sender,instance,**kwargs):
    instance.usercart_id.total_price = instance.usercart_id.get_total_price()
    instance.usercart_id.save()

@receiver(post_save,sender=UserCartProducts)
def update_cart_total_price_on_quantity_changed(sender,instance,**kwargs):
    if kwargs['update_fields']== None or instance.pk and 'quantity' in kwargs['update_fields']:
        instance.usercart_id.total_price = instance.usercart_id.get_total_price()
        instance.usercart_id.save()

@receiver(post_delete,sender=UserCartProducts)
@receiver(post_save,sender=UserCartProducts)
def update_status(sender,instance,**kwargs):
    if instance.usercart_id.total_price == 0.00:
        instance.usercart_id.status = 'inactive'
        instance.usercart_id.save()
    else:
        instance.usercart_id.status = 'active'
        instance.usercart_id.save()

TimeZoneApp/forms.py
from django import forms
from . import models


class CreateContact(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = ['name', 'email', 'subject', 'content']

    def __init__(self, *args, **kwargs):
        super(CreateContact, self).__init__(*args, **kwargs)
        self.fields['content'].widget.attrs.update({
            'class': 'form-control w-100',
            'name': 'message',
            'id': 'message',
            'cols': 30,
            'rows': 9,
            'onfocus': "this.placeholder = ''",
            'onblur': "this.placeholder = 'Enter Message'",
            'placeholder': 'Enter Message',
        })


class CreateProduct(forms.ModelForm):
    class Meta:
        model = models.Product
        fields = ['product_name', 'product_brand', 'product_price', 'product_stocks', 'product_thumbnail', 'product_description',]

    def __init__(self, *args, **kwargs):
        super(CreateProduct, self).__init__(*args, **kwargs)
        self.fields['product_description'].widget.attrs.update({
            'class': 'single-textarea',
            'name': 'description',
            'id': 'description',
            'cols': 30,
            'rows': 9,
            'onfocus': "this.placeholder = ''",
            'onblur': "this.placeholder = 'Description'",
            'placeholder': 'Description',
        })
        self.fields['product_price'].widget.attrs.update({
            'class': 'single-input',
            'onfocus': "this.placeholder = ''",
            'onblur': "this.placeholder = 'Price'",
            'placeholder': 'Price',
        })


class ProductImages(forms.ModelForm):

    class Meta:
        model = models.ProductImages
        fields = ['images']

class CreateAddress(forms.ModelForm):

    class Meta:
        model = models.Address
        fields = '__all__'

TimeZoneApp/templates/watches/about.html
{% extends 'watches/base.html' %}
{% load static %}
{% block main_content %}
     <main>
        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>About Us</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero Area End-->
        <!-- About Details Start -->
        <div class="about-details section-padding30">
            <div class="container">
                <div class="row">
                    <div class="offset-xl-1 col-lg-8">
                        <div class="about-details-cap mb-50">
                            <h4>Our Mission</h4>
                            <p>Consectetur adipiscing elit, sued do eiusmod tempor ididunt udfgt labore et dolore magna aliqua. Quis ipsum suspendisces gravida. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus.
                            </p>
                            <p> Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan.</p>
                        </div>

                        <div class="about-details-cap mb-50">
                            <h4>Our Vision</h4>
                            <p>Consectetur adipiscing elit, sued do eiusmod tempor ididunt udfgt labore et dolore magna aliqua. Quis ipsum suspendisces gravida. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus.
                            </p>
                            <p> Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan lacus. Risus commodo viverra sebfd dho eiusmod tempor maecenas accumsan.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- About Details End -->
        <!--? Video Area Start -->
        <div class="video-area mb-100">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-lg-12">
                    <div class="video-wrap">
                        <div class="play-btn "><a class="popup-video" href="https://www.youtube.com/watch?v=KMc6DyEJp04"><i class="fas fa-play"></i></a></div>
                    </div>
                    </div>
                </div>
                <!-- Arrow -->
                <div class="thumb-content-box">
                    <div class="thumb-content">
                        <h3>Next Video</h3>
                        <a href="#"> <i class="flaticon-arrow"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Video Area End -->
        <!--? Shop Method Start-->
        <div class="shop-method-area">
            <div class="container">
                <div class="method-wrapper">
                    <div class="row d-flex justify-content-between">
                        <div class="col-xl-4 col-lg-4 col-md-6">
                            <div class="single-method mb-40">
                                <i class="ti-package"></i>
                                <h6>Free Shipping Method</h6>
                                <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-6">
                            <div class="single-method mb-40">
                                <i class="ti-unlock"></i>
                                <h6>Secure Payment System</h6>
                                <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                            </div>
                        </div>
                        <div class="col-xl-4 col-lg-4 col-md-6">
                            <div class="single-method mb-40">
                                <i class="ti-reload"></i>
                                <h6>Secure Payment System</h6>
                                <p>aorem ixpsacdolor sit ameasecur adipisicing elitsf edasd.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Shop Method End-->
    </main>
{% endblock %}

TimeZoneApp/templates/watches/add_product.html
{% extends 'watches/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block main_content %}
    <main>
		<!-- Hero Area Start-->
		<div class="slider-area ">
			<div class="single-slider slider-height2 d-flex align-items-center">
				<div class="container">
					<div class="row">
						<div class="col-xl-12">
							<div class="hero-cap text-center">
								<h2>Add Products</h2>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="whole-wrap">
			<div class="container box_1170">
				<div class="section-top-border">
					<div class="row">
						<div class="col-lg-8 col-md-8">
							<h3 class="mb-30">Watch Details</h3>
							<form method="post" action="" enctype="multipart/form-data">
                                {% csrf_token %}
								<div class="mt-10">
									<input type="text" name="product_name" placeholder="Product Name" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Product Name'" class="single-input">
								</div>
								<div class="mt-10">
									<input type="text" name="product_brand" placeholder="Brand" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Brand'" class="single-input" required>
								</div>
								<div class="mt-10">
                                    <input type="number" name="product_price" step="0.01" class="single-input" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Price'" placeholder="Price" required="">
                                </div>
                                <div class="mt-10">
                                    <input type="number" name="product_stocks" min="1" step="1" onkeypress="return event.charCode >= 48 && event.charCode <= 57" value="{{ form.product_stocks.value|default_if_none:'' }}" class="single-input" placeholder="Stocks" required>
								</div>
								<div class="mt-10">
                                    <textarea name="product_description" cols="30" rows="9" class="single-textarea" id="description" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Description'" placeholder="Description" required="" spellcheck="false"></textarea>
								</div>
								<div class="mt-10">
                                    <figure class="single-popular-items mb-50">
                                        <img id="chosen-image" style="max-height: 400px;max-width: 325px;">
                                    </figure>
									{% render_field form.product_thumbnail id="upload-button" class="genric-btn" style="display: none;" %}
                                    <label for="upload-button" class="genric-btn danger-border" onmouseover="this.style.color='white'" onmouseleave="this.style.color='#f44a40'">
                                        <i class="fa-sharp fa-solid fa-arrow-up-from-bracket"></i> Choose a Thumbnail</label>
								</div>
                                <div class="mt-10">
                                    <div id="chosen-images" class="row gallery-item">

                                    </div>

									<input name="images" onchange="preview()" type="file" id="upload-button2" class="genric-btn info-border" style="display: none;" accept="image/*" multiple required>

									<label for="upload-button2" class="genric-btn danger-border" onmouseover="this.style.color='white'" onmouseleave="this.style.color='#f44a40'">
                                        <i class="fa-sharp fa-solid fa-arrow-up-from-bracket"></i> Choose a More Pics</label>
                                        <p id="num-of-files">No Files Selected</p>
								</div>
                                <button type="submit" value="submit" class="genric-btn info e-large"> Submit</button>
                                <input type="reset" class="genric-btn danger e-large">
                                <script src="{% static 'TimeZoneApp/js/myedits.js' %}"></script>


							</form>
						</div>

					</div>
				</div>
			</div>
		</div>
		<!-- End Align Area -->
	</main>
{% endblock %}

{#<input type="file" name="product_thumbnail" id="upload-button" class="genric-btn" style="display: none;" accept="image/*" value="{{ form.product_thumbnail.value|default_if_none:''  }}" required>#}
{#                                    #}

TimeZoneApp/templates/watches/auth_success.html
{% extends "watches/base.html" %}
{% block main_content %}
    <main>
        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Email Verified</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero Area End-->
        <!--================login_part Area =================-->
        <section class="login_part section_padding ">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_text text-center">
                            <div class="login_part_text_iner">
                                <h2>Already a Member?</h2>
                                <p>There are advances being made in science and technology
                                    everyday, and a good example of this is the</p>
                                <a href="{% url 'login' %}" class="btn_3">Log in</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="single-defination">
								<h4 class="mb-20">Your email address is verified</h4>
								<p>Thanks for a confirming your email.
									</p>
                        </div>
                        <a href="{% url 'login' %}" class="btn_3">Go to Login</a>
                    </div>
                </div>
            </div>
        </section>
        <!--================login_part end =================-->
    </main>
{% endblock %}

TimeZoneApp/templates/watches/auth_token.html
{% extends "watches/base.html" %}
{% block main_content %}
    <main>
        <!-- Hero Area Start-->
        <div class="slider-area ">
            <div class="single-slider slider-height2 d-flex align-items-center">
                <div class="container">
                    <div class="row">
                        <div class="col-xl-12">
                            <div class="hero-cap text-center">
                                <h2>Email Confirmation</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Hero Area End-->
        <!--================login_part Area =================-->
        <section class="login_part section_padding ">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-6 col-md-6">
                        <div class="login_part_text text-center">
                            <div class="login_part_text_iner">
                                <h2>Already a Member?</h2>
                                <p>There are advances being made in science and technology
                                    everyday, and a good example of this is the</p>
                                <a href="{% url 'login' %}" class="btn_3">Log in</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-6">
                        <div class="single-defination">
								<h4 class="mb-20">Confirm your email address</h4>
								<p>Please check your inbox for a confirmation email. Click the link in the email to confirm your email address.
									</p>
							</div>
                    </div>
                </div>
            </div>
        </section>
        <!--================login_part end =================-->
    </main>
{% endblock %}

TimeZoneApp/templates/watches/product.html
{% extends 'watches/base.html' %}
{% load static %}

{% block maintitle %}
    <title>{{ product.product_name }}</title>
{% endblock %}

{% block main_content %}
  <main>
        <!--================Single Product Area =================-->
        <div class="product_image_area" style="margin-top: 50px;">
            <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="single_product_text text-center">
                        <h3>{{ product.product_name }}</h3>
                    </div>
                </div>
                <div class="col-lg-8">
                <div class="product_img_slide owl-carousel owl-loaded owl-drag">
                <div class="owl-stage-outer">
                    <div class="owl-stage" style="transform: translate3d(-4560px, 0px, 0px); transition: all 0.25s ease 0s; width: 7980px;">
                        {% for product_image in product.productimages_set.all %}
                        <div class="owl-item active" style="width: 1140px;">
                            <div class="single_product_img">
                                <img src="{{ product_image.images.url }}" alt="#" class="img-fluid">
                            </div>
                        </div>
                        {% endfor %}
                    </div></div>
                </div>
                    <div class="owl-nav">
                        <button type="button" role="presentation" class="owl-prev">
                            <i class="ti-angle-left"></i>
                        </button>
                        <button type="button" role="presentation" class="owl-next">
                            <i class="ti-angle-right"></i>
                        </button>
                    </div>
                    <div class="owl-dots disabled"></div>
                </div>
                <div class="col-lg-8">
                <div class="single_product_text text-center">
                    <h3>{{ product.product_name }}</h3>
                    <p>
                        {{ product.product_description }}
                    </p>
                    <div class="card_area">
                        <div class="product_count_area">
                            <p>Quantity</p>
                            <div class="product_count d-inline-block">
                                <span class="product_count_item inumber-decrement" onclick="changePrice();"> <i class="fa-tej fa-solid fa-minus fa-lg"></i></span>
                                <input id="product-quantity" class="product_count_item input-number" type="text" value="1" min="1" max="10">
                                <span class="product_count_item number-increment" onclick="changePrice();"> <i class="fa-tej fa-solid fa-plus fa-lg"></i></span>
                            </div>
                            <p>₹</p>
                            <p id="single-product-price" hidden>{{ product.product_price }}</p>
                            <p id="product-price">{{ product.product_price }}</p>
                        </div>
                    <div class="add_to_cart">
                        <a href="#" class="btn_3">add to cart</a>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            </div>
        </div>
        <!--================End Single Product Area =================-->
        <!-- subscribe part here -->
        <section class="subscribe_part section_padding">
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-8">
                        <div class="subscribe_part_content">
                            <h2>Get promotions & updates!</h2>
                            <p>Seamlessly empower fully researched growth strategies and interoperable internal or “organic” sources credibly innovate granular internal .</p>
                            <div class="subscribe_form">
                                <input type="email" placeholder="Enter your mail">
                                <a href="#" class="btn_1">Subscribe</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- subscribe part end -->
    </main>
{% endblock %}